services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:4000
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 [::1]"